### ISSUE TITLE
Create Settings View

### ISSUE THREAD

**Issue by SlayterDev** [Danwakeem/enigma#39]
Add a view to manage settings of the app and keyboard.

**Comment by SlayterDev** [comment]
Settings is just about done. But how do I make the status bar white???

**Comment by jakesinger** [comment]
Add `setNeedsStatusBarAppearanceUpdate` to `viewDidAppear`:
```swift
override func viewDidAppear(animated: Bool) {
    ...
    setNeedsStatusBarAppearanceUpdate()
}
```
And implement `preferredStatusBarStyle`:
```swift
override func preferredStatusBarStyle() -> UIStatusBarStyle {
    return .LightContent
}
```

**Comment by SlayterDev** [comment]
Ahhhh got it.

**Comment by SlayterDev** [comment]
Still a black status bar

**Comment by jakesinger** [comment]
Ah sorry, did not notice you had a navigation controller hooked up! In the storyboard, change the navigation bar for the settings view's navigation controller from "Default" to "Black". When views are presented inside a navigation controller, the status bar style is determined by it rather than the view itself.

**Comment by SlayterDev** [comment]
3e6d28dfd464ec6a5eb2a61fcb08f9012845849c

Done.
